#!/usr/bin/python
# -*- Mode:python; c-file-style:"gnu"; indent-tabs-mode:nil -*- */
#
# Copyright (C) 2014 Regents of the University of California.
# Author: Adeola Bannis
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# A copy of the GNU General Public License is in the file COPYING.

from __future__ import print_function
from ndn_pi.config.config_manager import ConfigManager
import sys
from optparse import OptionParser


parser = OptionParser(usage='Usage: %prog [-h] | [-c] | [-q] filename')
parser.add_option("-q", "--quick", action="store_true", 
    default=False, dest="quick_run", help="Quick: generate certificates only")
parser.add_option("-c", action="store_true", default=False, 
    dest="controller", help="Edit default controller configuration (may require sudo)")

(options, args) = parser.parse_args()



if options.quick_run:
    if len(args) == 0:
        parser.print_help()
        sys.exit(1)
    else:
        allFiles = args[1:]
    for fileName in allFiles:
        ConfigManager(fileName).quietMain()
else:
    if options.controller:
        if len(args) == 0:
            fileName = '/usr/local/etc/ndn/iot/controller.conf' 
        else:
            parser.print_help()
            sys.exit(1)
    else:
        if len(args) > 2:
            print("Ignoring extra args: {}".format(' '.join(args[2:])), file=sys.stderr)
        elif len(args) > 1:
            fileName = args[1]
        else:
            fileName = None

    ConfigManager(fileName).main()
