#!/usr/bin/python
# -*- Mode:python; c-file-style:"gnu"; indent-tabs-mode:nil -*- */
#
# Copyright (C) 2014 Regents of the University of California.
# Author: Adeola Bannis
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# A copy of the GNU General Public License is in the file COPYING.

from __future__ import print_function
from ndn_pi.config.config_manager import ConfigManager
import sys

def print_usage():
    usageStr = 'Usage: ndn-config [-h] [[-q] filename]\n'
    usageStr += '\t-h,--help\t\tPrint this message\n'
    usageStr += '\t-q\t\tQuick: generate certificates only\n'
    usageStr += '\tfilename\t\tThe configuration file to load\n'
    print(usageStr)

args = sys.argv[:]
if '-h' in args or '--help' in args:
    print_usage()
    sys.exit(0)

try:
    args.remove('-q')
except ValueError:
    quietMode = False
else:
    quietMode = True



if len(args) > 2:
        print("Ignoring extra args: {}".format(' '.join(sys.argv[2:])), file=sys.stderr)
if len(args) > 1:
        fileName = args[1]
else:
        fileName = None

if not quietMode:
    ConfigManager(fileName).main()
else:
    ConfigManager(fileName).quietMain()
