# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='add-user.proto',
  package='',
  serialized_pb='\n\x0e\x61\x64\x64-user.proto\"\x8c\x01\n\x15\x41\x64\x64UserRequestMessage\x12;\n\x0b\x63redentials\x18\xf1\x01 \x02(\x0b\x32%.AddUserRequestMessage.AddUserRequest\x1a\x36\n\x0e\x41\x64\x64UserRequest\x12\x11\n\x08userName\x18\xef\x01 \x02(\t\x12\x11\n\x08userPass\x18\xf0\x01 \x02(\t')




_ADDUSERREQUESTMESSAGE_ADDUSERREQUEST = descriptor.Descriptor(
  name='AddUserRequest',
  full_name='AddUserRequestMessage.AddUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='userName', full_name='AddUserRequestMessage.AddUserRequest.userName', index=0,
      number=239, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userPass', full_name='AddUserRequestMessage.AddUserRequest.userPass', index=1,
      number=240, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=105,
  serialized_end=159,
)

_ADDUSERREQUESTMESSAGE = descriptor.Descriptor(
  name='AddUserRequestMessage',
  full_name='AddUserRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='credentials', full_name='AddUserRequestMessage.credentials', index=0,
      number=241, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ADDUSERREQUESTMESSAGE_ADDUSERREQUEST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=159,
)

_ADDUSERREQUESTMESSAGE_ADDUSERREQUEST.containing_type = _ADDUSERREQUESTMESSAGE;
_ADDUSERREQUESTMESSAGE.fields_by_name['credentials'].message_type = _ADDUSERREQUESTMESSAGE_ADDUSERREQUEST
DESCRIPTOR.message_types_by_name['AddUserRequestMessage'] = _ADDUSERREQUESTMESSAGE

class AddUserRequestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class AddUserRequest(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ADDUSERREQUESTMESSAGE_ADDUSERREQUEST
    
    # @@protoc_insertion_point(class_scope:AddUserRequestMessage.AddUserRequest)
  DESCRIPTOR = _ADDUSERREQUESTMESSAGE
  
  # @@protoc_insertion_point(class_scope:AddUserRequestMessage)

# @@protoc_insertion_point(module_scope)
