# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='list-devices.proto',
  package='',
  serialized_pb='\n\x12list-devices.proto\"\xc9\x01\n\x19ListDevicesCommandMessage\x12?\n\x07\x63ommand\x18\xe1\x01 \x02(\x0b\x32-.ListDevicesCommandMessage.ListDevicesCommand\x1a\x1a\n\x04Name\x12\x12\n\ncomponents\x18\x08 \x03(\x0c\x1aO\n\x12ListDevicesCommand\x12\x39\n\x0f\x65nvironmentName\x18\xe0\x01 \x02(\x0b\x32\x1f.ListDevicesCommandMessage.Name')




_LISTDEVICESCOMMANDMESSAGE_NAME = descriptor.Descriptor(
  name='Name',
  full_name='ListDevicesCommandMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='components', full_name='ListDevicesCommandMessage.Name.components', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=143,
)

_LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND = descriptor.Descriptor(
  name='ListDevicesCommand',
  full_name='ListDevicesCommandMessage.ListDevicesCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='environmentName', full_name='ListDevicesCommandMessage.ListDevicesCommand.environmentName', index=0,
      number=224, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=145,
  serialized_end=224,
)

_LISTDEVICESCOMMANDMESSAGE = descriptor.Descriptor(
  name='ListDevicesCommandMessage',
  full_name='ListDevicesCommandMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='command', full_name='ListDevicesCommandMessage.command', index=0,
      number=225, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LISTDEVICESCOMMANDMESSAGE_NAME, _LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=224,
)

_LISTDEVICESCOMMANDMESSAGE_NAME.containing_type = _LISTDEVICESCOMMANDMESSAGE;
_LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND.fields_by_name['environmentName'].message_type = _LISTDEVICESCOMMANDMESSAGE_NAME
_LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND.containing_type = _LISTDEVICESCOMMANDMESSAGE;
_LISTDEVICESCOMMANDMESSAGE.fields_by_name['command'].message_type = _LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND
DESCRIPTOR.message_types_by_name['ListDevicesCommandMessage'] = _LISTDEVICESCOMMANDMESSAGE

class ListDevicesCommandMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Name(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LISTDEVICESCOMMANDMESSAGE_NAME
    
    # @@protoc_insertion_point(class_scope:ListDevicesCommandMessage.Name)
  
  class ListDevicesCommand(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LISTDEVICESCOMMANDMESSAGE_LISTDEVICESCOMMAND
    
    # @@protoc_insertion_point(class_scope:ListDevicesCommandMessage.ListDevicesCommand)
  DESCRIPTOR = _LISTDEVICESCOMMANDMESSAGE
  
  # @@protoc_insertion_point(class_scope:ListDevicesCommandMessage)

# @@protoc_insertion_point(module_scope)
