# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='symmetric-key.proto',
  package='',
  serialized_pb='\n\x13symmetric-key.proto\"\xaf\x01\n\x1aSymmetricKeyRequestMessage\x12\x41\n\x07request\x18\xee\x01 \x02(\x0b\x32/.SymmetricKeyRequestMessage.SymmetricKeyRequest\x1aN\n\x13SymmetricKeyRequest\x12\x12\n\tnotBefore\x18\xeb\x01 \x02(\r\x12\x11\n\x08notAfter\x18\xec\x01 \x02(\r\x12\x10\n\x07keyBits\x18\xed\x01 \x02(\x0c')




_SYMMETRICKEYREQUESTMESSAGE_SYMMETRICKEYREQUEST = descriptor.Descriptor(
  name='SymmetricKeyRequest',
  full_name='SymmetricKeyRequestMessage.SymmetricKeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='notBefore', full_name='SymmetricKeyRequestMessage.SymmetricKeyRequest.notBefore', index=0,
      number=235, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='notAfter', full_name='SymmetricKeyRequestMessage.SymmetricKeyRequest.notAfter', index=1,
      number=236, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keyBits', full_name='SymmetricKeyRequestMessage.SymmetricKeyRequest.keyBits', index=2,
      number=237, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=199,
)

_SYMMETRICKEYREQUESTMESSAGE = descriptor.Descriptor(
  name='SymmetricKeyRequestMessage',
  full_name='SymmetricKeyRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='request', full_name='SymmetricKeyRequestMessage.request', index=0,
      number=238, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYMMETRICKEYREQUESTMESSAGE_SYMMETRICKEYREQUEST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=199,
)

_SYMMETRICKEYREQUESTMESSAGE_SYMMETRICKEYREQUEST.containing_type = _SYMMETRICKEYREQUESTMESSAGE;
_SYMMETRICKEYREQUESTMESSAGE.fields_by_name['request'].message_type = _SYMMETRICKEYREQUESTMESSAGE_SYMMETRICKEYREQUEST
DESCRIPTOR.message_types_by_name['SymmetricKeyRequestMessage'] = _SYMMETRICKEYREQUESTMESSAGE

class SymmetricKeyRequestMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class SymmetricKeyRequest(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYMMETRICKEYREQUESTMESSAGE_SYMMETRICKEYREQUEST
    
    # @@protoc_insertion_point(class_scope:SymmetricKeyRequestMessage.SymmetricKeyRequest)
  DESCRIPTOR = _SYMMETRICKEYREQUESTMESSAGE
  
  # @@protoc_insertion_point(class_scope:SymmetricKeyRequestMessage)

# @@protoc_insertion_point(module_scope)
